### ISSUE TITLE
How to handle variable published names?

### ISSUE THREAD

**Issue by khanson679** [lingbib/lingbib#16]
Currently, all people have an entry in the database using their typical published name (as opposed to their full name, for example), which is linked with a YAML anchor/alias to all places it is needed in bibliographic entries.
Variant names are handled by simply inserting a person object literal in the necessary location.

This is probably not ideal.

Some relevant concerns:
-Ideally, variant publishing names should be stored in a centralized location as with canonical publishing names.
-Variant names should be connect to the relevant canonical name.
-Need to determine in advance what to do about cases where a particular name can refer to several different people.

Some unknowns:
-Is it necessary or desirable to store a person's full name in their main author entry, instead of or in addition to their canonical publishing name?
-How much, exactly, do we want to store about authors, beyond an ORCID and perhaps a URL?

**Comment by adamliter** [comment]
Regarding your first unknown, I think the ideal scenario would be that a person's full name is stored in the main person entry, and only the relevant information is pulled in for each citation. Hopefully(?) this could be done by annotating the (anchors of the) entries in some way? We would need to do this for editors as well as authors ...

Regarding your second unknown, I can't think of anything else we'd necessarily want.

**Comment by adamliter** [comment]
Actually, regarding the second unknown, there are a few other things that just occurred to me: academia.edu profiles, Google Scholar profiles, etc.. There seem to be a lot of similar services like this now. There's also Research Gate and SelectedWorks.

**Comment by khanson679** [comment]
Hmm. OK, we'll have to examine this a bit more thoroughly then.

>

**Comment by adamliter** [comment]
Some of those are more used than ORCID. Impressionistically, I'd say it'd go something like: 

> academia.edu, Google Scholar > Research Gate > ORCID, SelectedWorks

But that's a total guess based on my impression.

That being said, I don't think it'd be that difficult to support all of them. We can just leave it up to the user base to find the profiles but not necessarily require them when entries are submitted. I think the main requirement should be a person's website (if it exists).

**Comment by khanson679** [comment]
OK. So I'm toying with the idea of have these all go in an "ids" field, with subfields for each. Likewise for the name parts, the advantage here being a way of putting multiple names in an author entry. Still need to think about the implications carefully. There are many, many ways it could be done.

```yaml
#ex 1
noam_chomsky1:
  names:
    noam_chomsky:
      first:
      last:
      ...
    avril_noam_chomsky:
      first:
      last:
      ...
  ids:
    orcid: ...
    googlescholar: ...
    ...
  url: name@dept.int.edu

#ex2
noam_chomsky2:
  name:
      first:
      last:
      ...
  variants:
    avril_noam_chomsky:
      first:
      last:
      ...
  ids:
    orcid: ...
    googlescholar: ...
    ...
  url: name@dept.int.edu
```

**Comment by adamliter** [comment]
@khanson679 I like the idea of an "ids" field.

Between the two examples that you've given, I think I like the first option better (minus the `1` in the name of the object).

**Comment by khanson679** [comment]
Not sure about the anchors. Doing things this way, we still have not solved the problem of duplicate names. However, I'm still thinking about an alternative method of referencing data based on the document structure, relative to the root. Under such a system, each name would have a unique address, which when expressed in native Python would be:
```python
document['people']['noam_chomsky']['noam_chomsky']
```

There are existing methods to encode this in the data, such as JSON Reference, where it would be "#/people/noam_chomsky/noam_chomsky".

This is a bit verbose, but it avoids duplication of data, and requires only that the object for the author have a unique key. Keys for individual names, like "John Smith", can be shared, because their address will be prefixed by a unique key.

**Comment by khanson679** [comment]
There's another basic way to organize the person entries, which is to give up on putting every name in the person object, and instead link from variant name entries to main entries.
If you wanted too, you could also add a list of reference to alises to the main entry.
Example:

```yaml
people:
  noam_chomsky:
    name:
      first: Noam
      last: Chomsky
    aliases: [{"$ref": "#/people/avram_noam_chomsky"}]
    ids:
      orcid: ...
      googlescholar: ...
    url: name@dept.int.edu

aliases:
  avram_noam_chomsky:
    name:
      first: Avram
      middle: Noam
      last: Chomsky
    main_id: {"$ref": "#/people/noam_chomsky"}
```

Notice that the structure of the two types of entries is similar enough that a dumb parser/converter could just fetch the name from the person entry without checking whether it's an alias, while a smart one can go fetch the canonical name easily.
In both cases, it's one field deep.
References are short, too.

Again, something needs to be done about shared names. I fear that the solution will end up similar to the first.

**Comment by khanson679** [comment]
For the sake of completeness, I also considered how you would do this with option (1b), where all names are contained in one author, but differentiated by putting them in different fields.

```yaml
noam_chomsky2:
  name:
    first: Noam
    last: Chomsky
  aliases:
    avram_noam_chomsky:
      first: Avram
      middle: Noam
      last: Chomsky
  ids:
    orcid: ...
    googlescholar: ...
  url: name@dept.int.edu
```

Here, you could reference to the main name with "#/people/noam_chomsky/name", and the alias with "#/people/noam_chomsky/aliases/avram_noam_chomsky". 
In verbosity, this is an improvement over (1a).
It also reduces the volume of references (or anchors) and consolidates related information compared to (2).
I think it's still a candidate worth considering.

**Comment by khanson679** [comment]
I have two partially written follow-up posts. But I may not get around to finishing them for a bit, so I'll let you see what I've said so far in the meantime.

**Comment by adamliter** [comment]
@khanson679 I still haven't really had a chance to play around with PyYAML or anything, but I do like your (1b) idea:

```yaml
noam_chomsky:
  name:
    first: Noam
    last: Chomsky
  aliases:
    avram_noam_chomsky:
      first: Avram
      middle: Noam
      last: Chomsky
  ids:
    orcid: ...
    googlescholar: ...
  url: name@dept.int.edu
```
It seems to me that a good advantage of this is that it keeps everything together. Also, as you say, it reduces the verbosity.

But, like I said, I haven't played around with the software yet, so I'm not sure what other ramifications there might be.

**Comment by khanson679** [comment]
So, coming back to this issue after a long break, I think I do like (1b) best, both for the organization format itself and the fact that it really shouldn't be a problem to access names from bib entries, whether we use aliases, JSON references, or a custom solution.

**Comment by khanson679** [comment]
Here's a sketch of a solution with JSON references.

In the simple case, all you need to do is insert references to the the authors' names in place of objects.

```yaml
# Self-contained entry
  type: article
  title: An excellent paper on something
  author:
    - {first: "Alan", last: "Anderson"}
    - {first: "Bill", last: "Brown"}
    - {first: "Curt", last: "Clark"}
  ...

# References
anderson_etal_2000:
  type: article
  title: An excellent paper on something
  author:
    - {"$ref": "#/people/alan_anderson/name"}
    - {"$ref": "#/people/bill_brown/name"}
    - {"$ref": "#/people/curt_clark/name"}
  ...
```

To use a variant name, just address it accordingly. Since we will eventually have a GUI to assist data entry, the awkward syntax for the references is not a huge problem.

**Comment by khanson679** [comment]
An alternative that I've been thinking about is linking entire person objects into the author and editor fields, and separately specifying a variant name if applicable.

```yaml
people:
  alan_anderson:
    name: {first: Alan, last: Anderson}
    aliases:
      a_anderson: {first: A., last: Anderson}
  bill_brown:
    name: {first: Bill, last: Brown}
    aliases:
      b_brown: {first: B., last: Brown}
  curt_clark:
    name: {first: Curt, last: Clark}
    aliases:
      c_clark: {first: C., last: Clark}

entries:
  anderson_etal_2000:
    type: article
    title: An excellent paper on something
    author:
      - [{"$ref": "#/people/alan_anderson"}, as: a_anderson]
      - {"$ref": "#/people/bill_brown"}
      - {"$ref": "#/people/curt_clark"}
```

We then add an extra step during the conversion to `.bib` that inserts the canonical and variant names in the correct places. As a bonus, this eliminates the need to fill out the `sortname` field, which is sort of an implementation detail that contributors shouldn't have to bother with. ("Should I use the author or the editor for the `sortname`?")

I think this, or something similar, is quite feasible. It's also the correct solution, I think, in a serious database. That being said, I would still like to do some research into what systems meant for storage of bibliographic data (like in libraries, not reference management software) do.

**Comment by adamliter** [comment]
I think the last example where you have different aliases will be necessary for people who publish under different names. And writing something to automagically fill in the `sortname` field when necessary also sounds good and should be straightforward to do given an example like what you have in your last comment.

This all sounds good to me! :+1:

Let me know if there's anything I can do to help with any of your research or anything. :smile:

**Comment by khanson679** [comment]
Update: made a small edit to my previous post to make the YAML syntactically valid.

And a slight clarification: is completely possible to support variant names under the first system:
> To use a variant name, just address it accordingly. 

But anyway we'll proceed in the direction of the second. It may be nice in the near future to make the format more concise and truly human-writable, by implicitly interpreting the author keys as such. Since we're already using "person" objects instead of dumb "name" objects, it won't take much more work. Example:
```yaml
entries:
  anderson_etal_2000:
    type: article
    title: An excellent paper on something
    author:
      - {person: alan_anderson, as: a_anderson}
      - {person: bill_brown}
      - {person: curt_clark}
```
